version: "3"

services:
  nextjs:
    container_name: nextjs
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../nextjs_app:/opt/nextjs_app